package nemty::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'nemty::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:radius',
        user => 'rady',
        password => 'Tac04@rabZ',
    },
    on_connect_call => 'use_foreign_keys',
);


=head1 NAME

nemty::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<nemty>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<nemty::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
